// Generated by scripts/gen-types.ts from supabase/migrations. Do not edit by hand.
// bigint columns are typed as number: PostgREST returns numbers, node-postgres returns strings (cast them).

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  ia_connect: {
    Tables: {
      access_requests: {
        Row: {
          id: string;
          user_id: string;
          full_name: string | null;
          company_name: string;
          sector: string;
          phone: string | null;
          message: string | null;
          status: string;
          decided_by: string | null;
          decided_at: string | null;
          decision_note: string | null;
          organization_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          full_name?: string | null;
          company_name: string;
          sector?: string;
          phone?: string | null;
          message?: string | null;
          status?: string;
          decided_by?: string | null;
          decided_at?: string | null;
          decision_note?: string | null;
          organization_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          full_name?: string | null;
          company_name?: string;
          sector?: string;
          phone?: string | null;
          message?: string | null;
          status?: string;
          decided_by?: string | null;
          decided_at?: string | null;
          decision_note?: string | null;
          organization_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      ai_calls: {
        Row: {
          id: string;
          organization_id: string;
          purpose: string;
          model: string;
          input_tokens: number;
          output_tokens: number;
          cost_micros: number;
          credits: number;
          flow_run_id: string | null;
          flow_run_step_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          purpose: string;
          model: string;
          input_tokens?: number;
          output_tokens?: number;
          cost_micros?: number;
          credits?: number;
          flow_run_id?: string | null;
          flow_run_step_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          purpose?: string;
          model?: string;
          input_tokens?: number;
          output_tokens?: number;
          cost_micros?: number;
          credits?: number;
          flow_run_id?: string | null;
          flow_run_step_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      appointments: {
        Row: {
          id: string;
          organization_id: string;
          contact_id: string | null;
          deal_id: string | null;
          connection_id: string | null;
          title: string;
          starts_at: string;
          ends_at: string;
          location: string | null;
          status: string;
          external_event_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          contact_id?: string | null;
          deal_id?: string | null;
          connection_id?: string | null;
          title: string;
          starts_at: string;
          ends_at: string;
          location?: string | null;
          status?: string;
          external_event_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          contact_id?: string | null;
          deal_id?: string | null;
          connection_id?: string | null;
          title?: string;
          starts_at?: string;
          ends_at?: string;
          location?: string | null;
          status?: string;
          external_event_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      approvals: {
        Row: {
          id: string;
          organization_id: string;
          flow_run_id: string;
          step_id: string;
          summary: string;
          status: string;
          decided_by: string | null;
          decided_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          flow_run_id: string;
          step_id: string;
          summary: string;
          status?: string;
          decided_by?: string | null;
          decided_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          flow_run_id?: string;
          step_id?: string;
          summary?: string;
          status?: string;
          decided_by?: string | null;
          decided_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      audit_log: {
        Row: {
          id: string;
          organization_id: string | null;
          actor_type: string;
          actor_id: string | null;
          action: string;
          entity_type: string | null;
          entity_id: string | null;
          data: Json;
          is_support_access: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id?: string | null;
          actor_type: string;
          actor_id?: string | null;
          action: string;
          entity_type?: string | null;
          entity_id?: string | null;
          data?: Json;
          is_support_access?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string | null;
          actor_type?: string;
          actor_id?: string | null;
          action?: string;
          entity_type?: string | null;
          entity_id?: string | null;
          data?: Json;
          is_support_access?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      connection_secrets: {
        Row: {
          id: string;
          organization_id: string;
          connection_id: string;
          vault_secret_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          connection_id: string;
          vault_secret_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          connection_id?: string;
          vault_secret_id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      connections: {
        Row: {
          id: string;
          organization_id: string;
          connector_type: string;
          name: string;
          status: string;
          config: Json;
          external_account_id: string | null;
          last_checked_at: string | null;
          last_error: string | null;
          webhook_token: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          connector_type: string;
          name: string;
          status?: string;
          config?: Json;
          external_account_id?: string | null;
          last_checked_at?: string | null;
          last_error?: string | null;
          webhook_token?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          connector_type?: string;
          name?: string;
          status?: string;
          config?: Json;
          external_account_id?: string | null;
          last_checked_at?: string | null;
          last_error?: string | null;
          webhook_token?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      connector_types: {
        Row: {
          key: string;
          category: string;
          name: string;
          description: string;
          connect_mode: string;
          config_schema: Json;
          allowed_plans: string[] | null;
          is_enabled: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          key: string;
          category: string;
          name: string;
          description?: string;
          connect_mode: string;
          config_schema?: Json;
          allowed_plans?: string[] | null;
          is_enabled?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          key?: string;
          category?: string;
          name?: string;
          description?: string;
          connect_mode?: string;
          config_schema?: Json;
          allowed_plans?: string[] | null;
          is_enabled?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      contacts: {
        Row: {
          id: string;
          organization_id: string;
          full_name: string;
          phones: string[];
          emails: string[];
          consents: Json;
          custom_fields: Json;
          external_ids: Json;
          memory: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          full_name?: string;
          phones?: string[];
          emails?: string[];
          consents?: Json;
          custom_fields?: Json;
          external_ids?: Json;
          memory?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          full_name?: string;
          phones?: string[];
          emails?: string[];
          consents?: Json;
          custom_fields?: Json;
          external_ids?: Json;
          memory?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      conversations: {
        Row: {
          id: string;
          organization_id: string;
          contact_id: string;
          channel: string;
          connection_id: string | null;
          status: string;
          assignee_type: string;
          assignee_user_id: string | null;
          external_thread_id: string | null;
          window_expires_at: string | null;
          last_message_at: string | null;
          unread_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          contact_id: string;
          channel: string;
          connection_id?: string | null;
          status?: string;
          assignee_type?: string;
          assignee_user_id?: string | null;
          external_thread_id?: string | null;
          window_expires_at?: string | null;
          last_message_at?: string | null;
          unread_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          contact_id?: string;
          channel?: string;
          connection_id?: string | null;
          status?: string;
          assignee_type?: string;
          assignee_user_id?: string | null;
          external_thread_id?: string | null;
          window_expires_at?: string | null;
          last_message_at?: string | null;
          unread_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      deal_events: {
        Row: {
          id: string;
          organization_id: string;
          deal_id: string;
          type: string;
          from_stage_id: string | null;
          to_stage_id: string | null;
          actor_type: string;
          actor_id: string | null;
          data: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          deal_id: string;
          type: string;
          from_stage_id?: string | null;
          to_stage_id?: string | null;
          actor_type: string;
          actor_id?: string | null;
          data?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          deal_id?: string;
          type?: string;
          from_stage_id?: string | null;
          to_stage_id?: string | null;
          actor_type?: string;
          actor_id?: string | null;
          data?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      deal_stages: {
        Row: {
          id: string;
          organization_id: string;
          key: string;
          name: string;
          position: number;
          kind: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          key: string;
          name: string;
          position?: number;
          kind?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          key?: string;
          name?: string;
          position?: number;
          kind?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      deals: {
        Row: {
          id: string;
          organization_id: string;
          contact_id: string;
          title: string;
          stage_id: string;
          estimated_value_cents: number | null;
          currency: string;
          origin_flow_run_id: string | null;
          next_action: string | null;
          next_action_at: string | null;
          assignee_user_id: string | null;
          custom_fields: Json;
          closed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          contact_id: string;
          title: string;
          stage_id: string;
          estimated_value_cents?: number | null;
          currency?: string;
          origin_flow_run_id?: string | null;
          next_action?: string | null;
          next_action_at?: string | null;
          assignee_user_id?: string | null;
          custom_fields?: Json;
          closed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          contact_id?: string;
          title?: string;
          stage_id?: string;
          estimated_value_cents?: number | null;
          currency?: string;
          origin_flow_run_id?: string | null;
          next_action?: string | null;
          next_action_at?: string | null;
          assignee_user_id?: string | null;
          custom_fields?: Json;
          closed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      events: {
        Row: {
          id: string;
          organization_id: string;
          type: string;
          connection_id: string | null;
          payload: Json;
          contact_hint: Json | null;
          dedupe_key: string;
          status: string;
          attempts: number;
          locked_until: string | null;
          available_at: string;
          error: string | null;
          occurred_at: string;
          processed_at: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          type: string;
          connection_id?: string | null;
          payload?: Json;
          contact_hint?: Json | null;
          dedupe_key: string;
          status?: string;
          attempts?: number;
          locked_until?: string | null;
          available_at?: string;
          error?: string | null;
          occurred_at?: string;
          processed_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          type?: string;
          connection_id?: string | null;
          payload?: Json;
          contact_hint?: Json | null;
          dedupe_key?: string;
          status?: string;
          attempts?: number;
          locked_until?: string | null;
          available_at?: string;
          error?: string | null;
          occurred_at?: string;
          processed_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Relationships: [];
      };
      flow_run_steps: {
        Row: {
          id: string;
          organization_id: string;
          flow_run_id: string;
          step_id: string;
          idempotency_key: string;
          block: string;
          input: Json;
          output: Json;
          outlet: string | null;
          status: string;
          error: string | null;
          ai_cost_micros: number;
          duration_ms: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          flow_run_id: string;
          step_id: string;
          idempotency_key: string;
          block: string;
          input?: Json;
          output?: Json;
          outlet?: string | null;
          status: string;
          error?: string | null;
          ai_cost_micros?: number;
          duration_ms?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          flow_run_id?: string;
          step_id?: string;
          idempotency_key?: string;
          block?: string;
          input?: Json;
          output?: Json;
          outlet?: string | null;
          status?: string;
          error?: string | null;
          ai_cost_micros?: number;
          duration_ms?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      flow_runs: {
        Row: {
          id: string;
          organization_id: string;
          flow_id: string;
          flow_version_id: string;
          event_id: string | null;
          mode: string;
          status: string;
          current_step_id: string | null;
          context: Json;
          contact_id: string | null;
          conversation_id: string | null;
          deal_id: string | null;
          waiting_for: string | null;
          wait_until: string | null;
          attempts: number;
          locked_until: string | null;
          error: string | null;
          started_at: string;
          finished_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          flow_id: string;
          flow_version_id: string;
          event_id?: string | null;
          mode?: string;
          status?: string;
          current_step_id?: string | null;
          context?: Json;
          contact_id?: string | null;
          conversation_id?: string | null;
          deal_id?: string | null;
          waiting_for?: string | null;
          wait_until?: string | null;
          attempts?: number;
          locked_until?: string | null;
          error?: string | null;
          started_at?: string;
          finished_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          flow_id?: string;
          flow_version_id?: string;
          event_id?: string | null;
          mode?: string;
          status?: string;
          current_step_id?: string | null;
          context?: Json;
          contact_id?: string | null;
          conversation_id?: string | null;
          deal_id?: string | null;
          waiting_for?: string | null;
          wait_until?: string | null;
          attempts?: number;
          locked_until?: string | null;
          error?: string | null;
          started_at?: string;
          finished_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      flow_templates: {
        Row: {
          id: string;
          key: string;
          sector: string;
          name: string;
          description: string;
          definition: Json;
          requirements: Json;
          is_published: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          sector: string;
          name: string;
          description?: string;
          definition: Json;
          requirements?: Json;
          is_published?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          sector?: string;
          name?: string;
          description?: string;
          definition?: Json;
          requirements?: Json;
          is_published?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      flow_versions: {
        Row: {
          id: string;
          organization_id: string;
          flow_id: string;
          version: number;
          definition: Json;
          author_type: string;
          author_id: string | null;
          note: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          flow_id: string;
          version: number;
          definition: Json;
          author_type: string;
          author_id?: string | null;
          note?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          flow_id?: string;
          version?: number;
          definition?: Json;
          author_type?: string;
          author_id?: string | null;
          note?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      flows: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          description: string;
          status: string;
          active_version_id: string | null;
          trigger_event: string | null;
          template_key: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          description?: string;
          status?: string;
          active_version_id?: string | null;
          trigger_event?: string | null;
          template_key?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          name?: string;
          description?: string;
          status?: string;
          active_version_id?: string | null;
          trigger_event?: string | null;
          template_key?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      invitations: {
        Row: {
          id: string;
          organization_id: string;
          email: string;
          role: string;
          status: string;
          invited_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          email: string;
          role: string;
          status?: string;
          invited_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          email?: string;
          role?: string;
          status?: string;
          invited_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      memberships: {
        Row: {
          id: string;
          user_id: string;
          organization_id: string | null;
          reseller_id: string | null;
          role: string;
          permissions: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          organization_id?: string | null;
          reseller_id?: string | null;
          role: string;
          permissions?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          organization_id?: string | null;
          reseller_id?: string | null;
          role?: string;
          permissions?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      message_templates: {
        Row: {
          id: string;
          organization_id: string;
          channel: string;
          name: string;
          language: string;
          subject: string | null;
          body: string;
          approval_status: string;
          external_name: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          channel: string;
          name: string;
          language?: string;
          subject?: string | null;
          body: string;
          approval_status?: string;
          external_name?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          channel?: string;
          name?: string;
          language?: string;
          subject?: string | null;
          body?: string;
          approval_status?: string;
          external_name?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      messages: {
        Row: {
          id: string;
          organization_id: string;
          conversation_id: string;
          direction: string;
          channel: string;
          content: string;
          meta: Json;
          template_id: string | null;
          ai_generated: boolean;
          ai_model: string | null;
          delivery_status: string;
          external_id: string | null;
          flow_run_id: string | null;
          sent_by_user_id: string | null;
          error: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          conversation_id: string;
          direction: string;
          channel: string;
          content?: string;
          meta?: Json;
          template_id?: string | null;
          ai_generated?: boolean;
          ai_model?: string | null;
          delivery_status?: string;
          external_id?: string | null;
          flow_run_id?: string | null;
          sent_by_user_id?: string | null;
          error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          conversation_id?: string;
          direction?: string;
          channel?: string;
          content?: string;
          meta?: Json;
          template_id?: string | null;
          ai_generated?: boolean;
          ai_model?: string | null;
          delivery_status?: string;
          external_id?: string | null;
          flow_run_id?: string | null;
          sent_by_user_id?: string | null;
          error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          organization_id: string;
          kind: string;
          title: string;
          body: string;
          link: string | null;
          read_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          kind?: string;
          title: string;
          body?: string;
          link?: string | null;
          read_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          kind?: string;
          title?: string;
          body?: string;
          link?: string | null;
          read_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      org_features: {
        Row: {
          id: string;
          organization_id: string;
          feature_key: string;
          enabled: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          feature_key: string;
          enabled?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          feature_key?: string;
          enabled?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      org_settings: {
        Row: {
          id: string;
          organization_id: string;
          language: string;
          ai_tone: string | null;
          ai_instructions: string | null;
          out_of_scope_reply: string;
          ai_disclosure: string;
          brand: Json;
          deal_custom_fields: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          language?: string;
          ai_tone?: string | null;
          ai_instructions?: string | null;
          out_of_scope_reply?: string;
          ai_disclosure?: string;
          brand?: Json;
          deal_custom_fields?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          language?: string;
          ai_tone?: string | null;
          ai_instructions?: string | null;
          out_of_scope_reply?: string;
          ai_disclosure?: string;
          brand?: Json;
          deal_custom_fields?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      organizations: {
        Row: {
          id: string;
          reseller_id: string;
          name: string;
          sector: string;
          plan_id: string;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          reseller_id: string;
          name: string;
          sector?: string;
          plan_id: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          reseller_id?: string;
          name?: string;
          sector?: string;
          plan_id?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      payment_requests: {
        Row: {
          id: string;
          organization_id: string;
          contact_id: string | null;
          deal_id: string | null;
          connection_id: string | null;
          amount_cents: number;
          currency: string;
          description: string;
          status: string;
          external_id: string | null;
          url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          contact_id?: string | null;
          deal_id?: string | null;
          connection_id?: string | null;
          amount_cents: number;
          currency?: string;
          description?: string;
          status?: string;
          external_id?: string | null;
          url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          contact_id?: string | null;
          deal_id?: string | null;
          connection_id?: string | null;
          amount_cents?: number;
          currency?: string;
          description?: string;
          status?: string;
          external_id?: string | null;
          url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      plans: {
        Row: {
          id: string;
          key: string;
          name: string;
          limits: Json;
          price_monthly_cents: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          name: string;
          limits: Json;
          price_monthly_cents?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          name?: string;
          limits?: Json;
          price_monthly_cents?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      resellers: {
        Row: {
          id: string;
          name: string;
          slug: string;
          brand: Json;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          brand?: Json;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          brand?: Json;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      scheduled_jobs: {
        Row: {
          id: string;
          organization_id: string | null;
          kind: string;
          payload: Json;
          run_at: string;
          status: string;
          attempts: number;
          locked_until: string | null;
          last_error: string | null;
          flow_run_id: string | null;
          dedupe_key: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id?: string | null;
          kind: string;
          payload?: Json;
          run_at: string;
          status?: string;
          attempts?: number;
          locked_until?: string | null;
          last_error?: string | null;
          flow_run_id?: string | null;
          dedupe_key?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string | null;
          kind?: string;
          payload?: Json;
          run_at?: string;
          status?: string;
          attempts?: number;
          locked_until?: string | null;
          last_error?: string | null;
          flow_run_id?: string | null;
          dedupe_key?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Relationships: [];
      };
      scrape_recipe_versions: {
        Row: {
          id: string;
          organization_id: string;
          recipe_id: string;
          version: number;
          recipe: Json;
          generated_by: string;
          note: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          recipe_id: string;
          version: number;
          recipe: Json;
          generated_by: string;
          note?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          recipe_id?: string;
          version?: number;
          recipe?: Json;
          generated_by?: string;
          note?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      scrape_recipes: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          target_url: string;
          goal: string;
          connection_id: string | null;
          status: string;
          active_version_id: string | null;
          interval_minutes: number;
          repair_attempts: number;
          last_run_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          target_url: string;
          goal?: string;
          connection_id?: string | null;
          status?: string;
          active_version_id?: string | null;
          interval_minutes?: number;
          repair_attempts?: number;
          last_run_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          name?: string;
          target_url?: string;
          goal?: string;
          connection_id?: string | null;
          status?: string;
          active_version_id?: string | null;
          interval_minutes?: number;
          repair_attempts?: number;
          last_run_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      scrape_runs: {
        Row: {
          id: string;
          organization_id: string;
          recipe_id: string;
          recipe_version_id: string | null;
          status: string;
          rows_extracted: number;
          new_rows: number;
          error: string | null;
          needed_repair: boolean;
          started_at: string;
          finished_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          recipe_id: string;
          recipe_version_id?: string | null;
          status: string;
          rows_extracted?: number;
          new_rows?: number;
          error?: string | null;
          needed_repair?: boolean;
          started_at?: string;
          finished_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          recipe_id?: string;
          recipe_version_id?: string | null;
          status?: string;
          rows_extracted?: number;
          new_rows?: number;
          error?: string | null;
          needed_repair?: boolean;
          started_at?: string;
          finished_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      signature_requests: {
        Row: {
          id: string;
          organization_id: string;
          contact_id: string | null;
          deal_id: string | null;
          connection_id: string | null;
          title: string;
          document_url: string;
          status: string;
          external_id: string | null;
          url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          contact_id?: string | null;
          deal_id?: string | null;
          connection_id?: string | null;
          title: string;
          document_url: string;
          status?: string;
          external_id?: string | null;
          url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          contact_id?: string | null;
          deal_id?: string | null;
          connection_id?: string | null;
          title?: string;
          document_url?: string;
          status?: string;
          external_id?: string | null;
          url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      support_sessions: {
        Row: {
          id: string;
          organization_id: string;
          admin_user_id: string;
          reason: string;
          started_at: string;
          ended_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          admin_user_id: string;
          reason?: string;
          started_at?: string;
          ended_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          admin_user_id?: string;
          reason?: string;
          started_at?: string;
          ended_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      usage_counters: {
        Row: {
          id: string;
          organization_id: string;
          period: string;
          metric: string;
          value: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          period: string;
          metric: string;
          value?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          period?: string;
          metric?: string;
          value?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      accept_invitations: { Args: Record<string, never>; Returns: number };
      quota_left: { Args: { p_org: string; p_metric: string }; Returns: number | null };
      consume_quota: { Args: { p_org: string; p_metric: string; p_amount?: number }; Returns: boolean };
      add_usage: { Args: { p_org: string; p_metric: string; p_amount: number }; Returns: undefined };
      export_contact: { Args: { p_contact: string }; Returns: Json };
      export_organization: { Args: { p_org: string }; Returns: Json };
      delete_organization: { Args: { p_org: string }; Returns: undefined };
      admin_delete_organization: { Args: { p_org: string }; Returns: undefined };
      log_action: {
        Args: { p_org: string; p_action: string; p_entity_type?: string | null; p_entity_id?: string | null; p_data?: Json };
        Returns: undefined;
      };
      save_connection: {
        Args: { p_actor: string; p_organization: string; p_connection: string | null; p_values: Json };
        Returns: Database["ia_connect"]["Tables"]["connections"]["Row"];
      };
      remove_connection: {
        Args: { p_actor: string; p_organization: string; p_connection: string };
        Returns: undefined;
      };
      store_connection_secret: { Args: { p_connection: string; p_secret: Json }; Returns: undefined };
      read_connection_secret: { Args: { p_connection: string }; Returns: Json };
      request_access: {
        Args: {
          p_full_name: string | null;
          p_company_name: string;
          p_sector: string;
          p_phone: string | null;
          p_message: string | null;
        };
        Returns: Database["ia_connect"]["Tables"]["access_requests"]["Row"];
      };
      decide_access_request: {
        Args: { p_request: string; p_approve: boolean; p_plan_key?: string; p_note?: string | null };
        Returns: Database["ia_connect"]["Tables"]["access_requests"]["Row"];
      };
      is_platform_admin: { Args: Record<string, never>; Returns: boolean };
      can_manage_org: { Args: { p_org: string }; Returns: boolean };
      has_org_access: { Args: { p_org: string }; Returns: boolean };
    };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
}

type Tables = Database["ia_connect"]["Tables"];
export type Row<T extends keyof Tables> = Tables[T]["Row"];
export type InsertRow<T extends keyof Tables> = Tables[T]["Insert"];
export type UpdateRow<T extends keyof Tables> = Tables[T]["Update"];
