/** Generates the SQL seed for `flow_templates` from packages/core. Run: npm run gen:seed */
import { writeFileSync } from "node:fs";
import { FLOW_TEMPLATES } from "../packages/core/src/index";

const quote = (value: string) => `'${value.replace(/'/g, "''")}'`;

export function renderSeed(): string {
  const rows = FLOW_TEMPLATES.map(
    (template) =>
      `  (${quote(template.key)}, ${quote(template.sector)}, ${quote(template.name)}, ${quote(template.description)},\n   ${quote(JSON.stringify(template.definition))}::jsonb,\n   ${quote(JSON.stringify(template.requirements))}::jsonb, true)`,
  );
  return `-- Generated by scripts/gen-seed.ts from packages/core/src/flow/templates.ts. Do not edit by hand.
insert into ia_connect.flow_templates (key, sector, name, description, definition, requirements, is_published) values
${rows.join(",\n")}
on conflict (key) do update set
  sector = excluded.sector, name = excluded.name, description = excluded.description,
  definition = excluded.definition, requirements = excluded.requirements, is_published = excluded.is_published;
`;
}

export const SEED_PATH = new URL("../supabase/migrations/20261004000400_flow_templates.sql", import.meta.url);

if (process.argv[1]?.endsWith("gen-seed.ts")) {
  writeFileSync(SEED_PATH, renderSeed());
  console.log(`Wrote ${SEED_PATH.pathname}`);
}
