/**
 * Generates TypeScript row types for the `ia_connect` schema by applying the
 * migrations to an in-memory Postgres and reading its catalog.
 * Run: npm run gen:types
 */
import { writeFileSync } from "node:fs";
import { createTestDb } from "../supabase/test/db";

const TYPES: Record<string, string> = {
  uuid: "string",
  text: "string",
  date: "string",
  "timestamp with time zone": "string",
  integer: "number",
  bigint: "number",
  boolean: "boolean",
  jsonb: "Json",
};

const db = await createTestDb();
const columns = await db.asService<{
  table_name: string;
  column_name: string;
  data_type: string;
  udt_name: string;
  is_nullable: string;
  column_default: string | null;
}>(
  `select table_name, column_name, data_type, udt_name, is_nullable, column_default
   from information_schema.columns where table_schema = 'ia_connect' order by table_name, ordinal_position`,
);
await db.close();

const tables = new Map<string, typeof columns>();
for (const column of columns)
  tables.set(column.table_name, [...(tables.get(column.table_name) ?? []), column]);

const tsType = (column: (typeof columns)[number]) => {
  if (column.data_type === "ARRAY") return column.udt_name === "_text" ? "string[]" : "unknown[]";
  const type = TYPES[column.data_type];
  if (!type)
    throw new Error(`Unmapped type ${column.data_type} on ${column.table_name}.${column.column_name}`);
  return type;
};

let out = `// Generated by scripts/gen-types.ts from supabase/migrations. Do not edit by hand.
// bigint columns are typed as number: PostgREST returns numbers, node-postgres returns strings (cast them).

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  ia_connect: {
    Tables: {
`;
for (const [name, cols] of tables) {
  const row = cols.map(
    (c) => `          ${c.column_name}: ${tsType(c)}${c.is_nullable === "YES" ? " | null" : ""};`,
  );
  const insert = cols.map((c) => {
    const optional = c.is_nullable === "YES" || c.column_default !== null;
    return `          ${c.column_name}${optional ? "?" : ""}: ${tsType(c)}${c.is_nullable === "YES" ? " | null" : ""};`;
  });
  const update = cols.map(
    (c) => `          ${c.column_name}?: ${tsType(c)}${c.is_nullable === "YES" ? " | null" : ""};`,
  );
  out += `      ${name}: {\n        Row: {\n${row.join("\n")}\n        };\n        Insert: {\n${insert.join("\n")}\n        };\n        Update: {\n${update.join("\n")}\n        };\n        Relationships: [];\n      };\n`;
}
out += `    };
    Views: { [_ in never]: never };
    Functions: {
      accept_invitations: { Args: Record<string, never>; Returns: number };
      quota_left: { Args: { p_org: string; p_metric: string }; Returns: number | null };
      consume_quota: { Args: { p_org: string; p_metric: string; p_amount?: number }; Returns: boolean };
      add_usage: { Args: { p_org: string; p_metric: string; p_amount: number }; Returns: undefined };
      export_contact: { Args: { p_contact: string }; Returns: Json };
      export_organization: { Args: { p_org: string }; Returns: Json };
      delete_organization: { Args: { p_org: string }; Returns: undefined };
      store_connection_secret: { Args: { p_connection: string; p_secret: Json }; Returns: undefined };
      read_connection_secret: { Args: { p_connection: string }; Returns: Json };
      is_platform_admin: { Args: Record<string, never>; Returns: boolean };
      can_manage_org: { Args: { p_org: string }; Returns: boolean };
      has_org_access: { Args: { p_org: string }; Returns: boolean };
    };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
}

type Tables = Database["ia_connect"]["Tables"];
export type Row<T extends keyof Tables> = Tables[T]["Row"];
export type InsertRow<T extends keyof Tables> = Tables[T]["Insert"];
export type UpdateRow<T extends keyof Tables> = Tables[T]["Update"];
`;
writeFileSync(new URL("../packages/core/src/database.gen.ts", import.meta.url), out);
console.log(`Generated types for ${tables.size} tables`);
